#!/bin/sh
mvn clean package && docker build -t kamlendupandey/MSAApp .
docker rm -f MSAApp 2>/dev/null || true && docker run -it --name MSAApp -p 8080:8080 -p 4848:4848 -p 8181:8181 --name MSAApp kamlendupandey/MSAApp
