---
apiVersion: v1
kind: Service
metadata:
  name: climage
  labels:
    app: climage
spec:
  type: NodePort
  selector:
    app: climage
  ports:
  - protocol: TCP
    port: 8080
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: climage
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: climage
    spec:
      containers:
      - name: clcontainer
        image: kamlendupandey/climage:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
