version: '2.3'
services:
  appcontainer:
    container_name: appcontainer
    image: appimage:latest
    ports:
     - 7080:8080  
    networks: 
        - inetwork
  clcontainer:
    container_name: clcontainer
    image: climage:latest
    ports:
     - 7060:8080
    networks: 
        - inetwork 
  database:
    container_name: database
    image: mysqldata
    volumes:
     - data:/var/lib/mysql
    ports:
     - "3406:3306"
    networks: 
        - inetwork

volumes: 
  data:
    driver: local
    name: newvolume

networks: 
  inetwork:
    driver: bridge
    name: mynetworks
