pipeline {
    agent any
	
	  tools
    {
       maven "Maven"
    }
 stages {
      stage('checkout') {
           steps {
             
                git branch: 'master', url: 'https://github.com/kamlendu/MicroProject.git'
             
          }
        }
	 stage('Execute Maven') {
           steps {
             	dir('MSAProject'){
                sh 'mvn package' 
                }            
          }
        }
        

  stage('Docker Build and Tag') {
           steps {
                dir('MSAProject'){
                docker-compose up -d
                }
             
          }
        }

    }
	}
