#!/bin/sh
mvn clean package && docker build -t kamlendupandey/MSAClient .
docker rm -f MSAClient 2>/dev/null || true && docker run -it --name MSAClient -p 8080:8080 -p 4848:4848 -p 8181:8181 --name MSAClient kamlendupandey/MSAClient
